### ISSUE TITLE
在安装uiautomator-client报错无法安装

### ISSUE THREAD

**Issue by testj** [macacajs/uiautomator-client#12]
报错日志为:
```
> uiautomator-client@1.0.16 install /Users/XXXXX/git/nvm/versions/node/v6.2.0/lib/node_modules/uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
Error: UI test projects can only target API 16 and above

/Users/XXXXX/git/nvm/versions/node/v6.2.0/lib/node_modules/uiautomator-client/scripts/build.js:164
      throw e;
      ^

Error: setup failed
    at ChildProcess.createProcess.on.code (/Users/feibaobao/git/nvm/versions/node/v6.2.0/lib/node_modules/uiautomator-client/scripts/build.js:120:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/feibaobao/git/nvm/versions/node/v6.2.0/bin/node" "/Users/XXXXX/git/nvm/versions/node/v6.2.0/bin/npm" "i" "uiautomator-client" "-g" "--save"
```

**Comment by xudafeng** [comment]
https://macacajs.github.io/macaca/faq.html
